complete -c _bait_style -f
complete -c _bait_style -s h -l help -d "Show help"
complete -c _bait_style -l style-border -x -d "Box outline styles"
complete -c _bait_style -l style-text -x -d "Text styles"
complete -c _bait_style -l margin -x -d "Box margins"
complete -c _bait_style -l padding -x -d "Box padding"
complete -c _bait_style -l align -x -a "center top bottom left right" -d "Text alignment"
complete -c _bait_style -l border -x -d "Text box outline"
complete -c _bait_style -l border -k -a round -d "╭──╮"
complete -c _bait_style -l border -k -a thin -d "┌──┐"
complete -c _bait_style -l border -k -a medium -d "┏━━┓"
complete -c _bait_style -l border -k -a double -d "╔══╗"
complete -c _bait_style -l border -k -a thick-inner -d "▗▄▄▖"
complete -c _bait_style -l border -k -a thick-outer -d "▛▀▀▜"
complete -c _bait_style -l border -k -a block -d "████"
